# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: layer|twenty|two
email: piotr@layer22.com
description: >- # this means to ignore newlines until "baseurl:"
  Functional Web Applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.layer22.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pusewicz

author:
  name: Piotr Usewicz
  image: https://www.gravatar.com/avatar/dcbf676f860477e44b275cae5d6318a4.jpg?s=288
  twitter: pusewicz
  github: pusewicz

timezone: Europe/Madrid

# Build settings
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-image-size
  - jekyll-last-modified-at
  - jekyll-loading-lazy
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-webp
  - jemoji

collections:
  - posts

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layout: archive
  layouts:
    year: archive_year
    month: archive_month
    day: archive_day
    tag: archive_tags
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'

permalink: "/:slug"

twitter:
  username: pusewicz
  card: summary_large_image

social:
  name: Piotr Usewicz
  links:
    - https://twitter.com/pusewicz
    - https://www.facebook.com/pusewicz
    - https://www.linkedin.com/in/PiotrUsewicz
    - https://github.com/pusewicz
    - https://keybase.io/pusewicz84
    - https://hellowelcome.club/@pusewicz

logo: /images/logo.png

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  style: compressed

webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/images", "/images/articles", "/images/articles/mov2gif"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _functions
  - .github
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
