source 'https://rubygems.org'

gem 'middleman', '~>3.3.0'

gem 'middleman-livereload', '~> 3.4.0'
gem 'middleman-blog'
gem 'middleman-deploy'
gem 'middleman-syntax'
gem 'middleman-autoprefixer'
gem 'middleman-meta-tags'
gem 'nokogiri'
gem 'redcarpet'
gem 'builder', '~> 3.0'
gem 'bourbon'
gem 'neat'
gem 'slim'
gem 'bitters'
